name: Bug report
description: Report a reproducible problem with tutr.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect to happen?
      placeholder: A concise description of the bug and expected behavior.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact commands, inputs, and environment details.
      placeholder: |
        1. Run `...`
        2. Enter `...`
        3. Observe `...`
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: tutr version
      description: Output of `uv run tutr -V` or installed package version.
      placeholder: 0.1.5
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/output
      description: Paste any traceback, stderr, or command output.
      render: shell
